function [ Hdist ] = GetHelli(theta, M, prob)
%GETHELLI Compute Hellinger distance between the model M with parameters theta, 
%         and probability vec prob. (for the small-scale network-data example) 
% Inputs:
%   theta   A column vector of parameters [beta0 beta1 lambda] to use in the CZO model.
%   CZO     A centered, zero/one type ALRsimple model with the appropriate graph and 
%           covariates.
%   prob    A probability vector such as generated by .ProbabiltyTable method of 
%           the ALR class.  Should be same length as rows of CZO.ProbabilityTable.


M.Beta = theta(1:2);
M.Lambda = theta(3);
tbl = M.ProbabilityTable;
Hdist = norm(sqrt(tbl.Probability)-sqrt(prob),2)/sqrt(2); 


end


